### ISSUE TITLE
Create Generator for Set, HashSet and TreeSet

### ISSUE THREAD

**Issue by HamzaBenyazid** [oubaydos/java-random-instances-generator#30]
Follow the pattern used in ListGenerator , MapGenerator in creating the three generators, and add their Enums in TypeEnum

**Comment by HamzaBenyazid** [comment]
And develop also their unit tests (similar to the list)

**Comment by HamzaBenyazid** [comment]
This was done in #53

**Comment by mosle77** [comment]
Hello
Why this ticket is closed?

Le lun. 30 oct. 2023 à 14:09, Benyazid Hamza ***@***.***> a
écrit :
