### ISSUE TITLE
Center configs in one place and create a builder for RandomInstanceGenerator

### ISSUE THREAD

**Issue by HamzaBenyazid** [oubaydos/java-random-instances-generator#59]
We have the maxCollectionSize and minCollectionSize configs in the collection generators, and if we added another config, it will be in the corresponding generator, which in my opinion not a good approach, and it will complicate things, like for the collection's generators we created an interface to manage that, we can avoid this complexity by centring the configs in the RandomInstanceGenerator class and creating a builder to give the user the possibility to change default values.

**Comment by HamzaBenyazid** [comment]
@oubaydos what do you think

**Comment by oubaydos** [comment]
@HamzaBenyazid  I dont get it. Can you provide some code of how the generator would be called.
If i understand correctly, isnt generate(generationClass,option) enough ?

**Comment by HamzaBenyazid** [comment]
I don't suggest changing the method calls, I just suggest having all configs in the RandomInstanceGenerator class and creating a builder to create its instances.
That means moving the minCollectionSize and maxCollectionSize config to RandomInstanceGenerator, and since we pass the RandomInstanceGenerator instance to the TypeGenerator, it will access all configs.
